return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "autotools-language-server",
      "clang-format",
      "clangd",
      "codelldb",
      "css-lsp",
      "deno",
      "elixir-ls",
      "gofumpt",
      "goimports",
      "gopls",
      "html-lsp",
      "lua-language-server",
      "prettier",
      "rust-analyzer",
      "rustywind",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "typescript-language-server",
      "zls",
    },
  },
}
